<?php

/**
 * @file
 * Helper module for Packaging tests. 
 */


/**
 * Implements hook_packaging_api().
 */
function packaging_test_packaging_api() {
  return array(
    'api' => '1.0',
    'path' => drupal_get_path('module', 'packaging_test') . '/strategies',
  );
}

/**
 * Implements hook_MODULE_PLUGIN().
 */
function packaging_test_packaging_strategy() {
  return array(
    'custom' => array(
      'label' => t('Custom'),
      'handler' => array(
        'class' => 'PackageCustomStrategy',
      ),
    ),
  );
}
